ext_demo.lo: /root/Code/php/php-7.3.12/ext/ext_demo/ext_demo.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/root/Code/php/php-7.3.12/ext/ext_demo $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /root/Code/php/php-7.3.12/ext/ext_demo/ext_demo.c -o ext_demo.lo 
$(phplibdir)/ext_demo.la: ./ext_demo.la
	$(LIBTOOL) --mode=install cp ./ext_demo.la $(phplibdir)

./ext_demo.la: $(shared_objects_ext_demo) $(EXT_DEMO_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_ext_demo) $(EXT_DEMO_SHARED_LIBADD)

